package com.jip.presentation;

import com.jip.data.InpatientData;
import com.jip.formatters.regex.RegexFormatter;
import com.jip.model.InpatientTableModel;
import com.jip.persistence.InpatientDBManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Yu Xiao
 */
public class InpatientPanel extends javax.swing.JPanel implements ActionListener {

    private final org.slf4j.Logger log = LoggerFactory.getLogger(this.getClass().getName());
    private InpatientData currentIpd = null;
    private List<InpatientData> ipds = null;
    private InpatientDBManager ipdbm;
    private InpatientTableModel iptm;
    private int selectedRow = -1;
    private int selectedCol = -1;
    
    String patientIDRegEx = "^[1-9]+$"; //digits only
    String numberRegEx = "(?<=^| )\\d+(\\.\\d+)?(?=$| )|(?<=^| )\\.\\d+(?=$| )";// allows 1, 1.1 and .1
    

//    NumberFormat format = NumberFormat.getCurrencyInstance(Locale.getDefault());
//    NumberFormatter formatter = new NumberFormatter(format);
    /**
     * Creates new form InpatientPanel
     */
    public InpatientPanel() {
        super();
        iptm = new InpatientTableModel();
        ipdbm = new InpatientDBManager(iptm);

        displayTable(0L);
        initComponents();
        initialTable();
        currentIpd = new InpatientData();
    }

    /**
     * Clear the display and create a blank patient object
     */
    public void clearInpatient() {

        tfPID.setText("");
        tfDateStay.setText("");
        tfRoomNumber.setText("");
        tfDailyRate.setText("");
        tfSupplies.setText("");
        tfServices.setText("");
    }

    private void saveInpatient() {
        try {
            int records = ipdbm.saveInpatientRecord(getInpatient());
            if (records == 0) {
                log.warn("There were no records saved.");
            }
            if (records > 1) {
                log.warn("More than one record was saved: " + records);
            }

        } catch (SQLException sqlex) {
            log.error("SQL Exception", sqlex.getMessage());
            sqlex.printStackTrace();
        }
    }

    /**
     * Fill the current inpatient object and return it
     *
     * @return the inpatient object
     */
    public InpatientData getInpatient() {

        currentIpd.setPatientId(Long.parseLong(tfPID.getText()));
        try {
            currentIpd.setDateOfStay((tfDateStay.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(InpatientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        currentIpd.setRoomNumber(tfRoomNumber.getText());
        currentIpd.setDailyRate(new BigDecimal(tfDailyRate.getText()));
        currentIpd.setSupplies(new BigDecimal(tfSupplies.getText()));
        currentIpd.setServices(new BigDecimal(tfServices.getText()));

        return currentIpd;
    }

    /**
     * Get the patientID for the table
     *
     * @return
     */
    public long getPatientIDFromForm() {

        return Long.parseLong(tfPID.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        tfRoomNumber = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        tfPID = new javax.swing.JFormattedTextField(new RegexFormatter(patientIDRegEx));
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tfDateStay = new javax.swing.JFormattedTextField(new SimpleDateFormat("yyyy-MM-dd"));
        tfServices = new javax.swing.JFormattedTextField(new RegexFormatter(numberRegEx));
        tfSupplies = new javax.swing.JFormattedTextField(new RegexFormatter(numberRegEx));
        tfDailyRate = new javax.swing.JFormattedTextField(new RegexFormatter(numberRegEx));
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inpatientTable = new javax.swing.JTable(iptm);
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(827, 644));

        tfRoomNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("PATIENT ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("DATE OF STAY");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ROOM NUMBER");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DAILY ROOM RATE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ROOM SERVICES");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ROOM SUPPLIES");

        tfPID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        tfDateStay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tfServices.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tfSupplies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tfDailyRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setText("(yyyy-mm-dd)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(tfRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDateStay, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(tfPID))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfServices, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(tfSupplies)
                            .addComponent(tfDailyRate)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnSave});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDateStay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfDailyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tfSupplies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClear)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfDateStay, tfPID, tfRoomNumber});

        jScrollPane1.setViewportView(inpatientTable);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(34, 34, 34)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction
        JButton source = (JButton) (evt.getSource());
        switch (source.getActionCommand()) {
            case "Save":
                saveInpatient();
                displayTable(getPatientIDFromForm());
                break;
            case "Clear":
                clearInpatient();
                break;
            case "Delete":
                ipdbm.deleteRow(selectedRow);
                break;
            case "Update":
                ipdbm.updateDB();
                break;

        }
    }//GEN-LAST:event_buttonAction

    private void initialTable() {
        // Select single, multiple, or multiple interval
        inpatientTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Configure to listen for row selection

        ListSelectionModel rowSM = inpatientTable.getSelectionModel();
        rowSM.addListSelectionListener(new RowListener());
    }

    private void displayTable(long pid) {
        try {

            ipdbm.fillTableModel(pid);

        } catch (SQLException ex) {
            log.error("SQL Exception", ex.getMessage());
        }
    }

    private void clearTable() {
//        DefaultTableModel model = (DefaultTableModel) inpatientTable.getModel();        
//        model.setRowCount(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnClear;
    javax.swing.JButton btnDelete;
    javax.swing.JButton btnSave;
    javax.swing.JButton btnUpdate;
    javax.swing.JTable inpatientTable;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JFormattedTextField tfDailyRate;
    javax.swing.JFormattedTextField tfDateStay;
    javax.swing.JTextField tfPID;
    javax.swing.JTextField tfRoomNumber;
    javax.swing.JFormattedTextField tfServices;
    javax.swing.JFormattedTextField tfSupplies;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
    }

    /**
     * Inner class that listens for row selection events
     */
    class RowListener implements ListSelectionListener {
        /*
         * (non-Javadoc)
         * 
         * @see
         * javax.swing.event.ListSelectionListener#valueChanged(javax.swing.
         * event.ListSelectionEvent)
         */

        @Override
        public void valueChanged(ListSelectionEvent e) {
            // Ignore extra messages.
            if (e.getValueIsAdjusting()) {
                return;
            }

            ListSelectionModel lsm = (ListSelectionModel) e.getSource();
            if (!lsm.isSelectionEmpty()) {
                selectedRow = lsm.getMinSelectionIndex();
            }
        }
    }
    /**
     * Inner class that listens for column events
     */
//    class ColumnListener implements ListSelectionListener {
//        /*
//         * (non-Javadoc)
//         * 
//         * @see
//         * javax.swing.event.ListSelectionListener#valueChanged(javax.swing.
//         * event.ListSelectionEvent)
//         */
//
//        @Override
//        public void valueChanged(ListSelectionEvent e) {
//            // Ignore extra messages.
//            if (e.getValueIsAdjusting()) {
//                return;
//            }
//
//            ListSelectionModel lsm = (ListSelectionModel) e.getSource();
//            if (!lsm.isSelectionEmpty()) {
//                selectedCol = lsm.getMinSelectionIndex();
//            }
//        }
//    }
}
