package com.jip.presentation;

import java.util.Locale;
import java.util.ResourceBundle;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Yu Xiao
 */
public class MainFrame extends javax.swing.JFrame {

     private final Logger log = LoggerFactory.getLogger(this.getClass().getName());
     private final ResourceBundle messages = ResourceBundle.getBundle("internationalization/MessagesBundle", Locale.getDefault());
     
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        super();  
       // Locale defaultLocale = Locale.getDefault();
       // Locale currentLocale = new Locale("fr", "CA");
            
        log.debug("Locale = " + Locale.getDefault());
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        com.jip.presentation.PatientPanel patientPanel1 = new com.jip.presentation.PatientPanel();
        com.jip.presentation.InpatientPanel inpatientPanel1 = new com.jip.presentation.InpatientPanel();
        com.jip.presentation.SurgicalPanel surgicalPanel1 = new com.jip.presentation.SurgicalPanel();
        com.jip.presentation.MedicationPanel medicationPanel1 = new com.jip.presentation.MedicationPanel();
        com.jip.presentation.ReportPanel reportPanel1 = new com.jip.presentation.ReportPanel();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JIP Management System");
        setResizable(false);

        jTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane.addTab(messages.getString("Patient"), patientPanel1);
        jTabbedPane.addTab(messages.getString("Inpatient"), inpatientPanel1);
        jTabbedPane.addTab(messages.getString("Surgical"), surgicalPanel1);
        jTabbedPane.addTab(messages.getString("Medication"), medicationPanel1);
        jTabbedPane.addTab(messages.getString("Report"), reportPanel1);

        getContentPane().add(jTabbedPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Exit");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenu jMenu1;
    javax.swing.JMenu jMenu2;
    javax.swing.JMenu jMenu3;
    javax.swing.JMenu jMenu4;
    javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
