package com.jip.presentation;

import com.jip.formatters.regex.RegexFormatter;
import com.jip.persistence.ReportDBManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * @author Yu Xiao
 */
public class ReportPanel extends javax.swing.JPanel {

    private ReportDBManager rdbm;
    String patientIDRegEx = "^[1-9]+$"; //digits only

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        rdbm = new ReportDBManager();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        tfPID = new javax.swing.JFormattedTextField(new RegexFormatter(patientIDRegEx));
        btnReport = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        reportPane1 = new javax.swing.JEditorPane();

        setPreferredSize(new java.awt.Dimension(827, 644));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("PATIENT ID: ");

        tfPID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnReport.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnReport.setText("Generate Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(tfPID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reportPane1.setEditable(false);
        reportPane1.setForeground(new java.awt.Color(109, 109, 109));
        jScrollPane1.setViewportView(reportPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateReport(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport
        try {
            String records = getReport(getPatientIDFromForm());

            if (records != null && records.length() > 0) {
                reportPane1.setText(records);
                reportPane1.setCaretPosition(1);
            } else {
                reportPane1.setText("No records to display.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_generateReport

    public String getReport(long patientID) throws SQLException {
        StringBuilder sb = new StringBuilder();
        sb.append("Report for Patient ID:  " + patientID);
        sb.append("\n\n==============================================");
        sb.append("\nThe inpatient charges:\n\n" + rdbm.getInpatientRecords(patientID));
        sb.append("The inpatient total charges is :" + rdbm.getInpatientTotalCharge(patientID));
        sb.append("\n\n==============================================");
        sb.append("\nThe surgical charges:\n\n" + rdbm.getSurgicalRecords(patientID));
        sb.append("The surgical total charges is :" + rdbm.getSurgicalTotalCharge(patientID));
        //sb.append(getSurgicalRecords(patientID));
        sb.append("\n\n==============================================");
        sb.append("\nThe medication charges:\n\n" + rdbm.getMedicationRecords(patientID));
        sb.append("The medication total charges is :" + rdbm.getMedicationTotalCharge(patientID));
        //sb.append(getMedicationRecords(patientID));
        sb.append("\n\n====================================================================");
        sb.append("\nThe total charges is :" + rdbm.getInpatientTotalCharge(patientID).add(rdbm.getMedicationTotalCharge(patientID)).add(rdbm.getSurgicalTotalCharge(patientID)));
        return sb.toString();
    }

    public long getPatientIDFromForm() {
        return Long.parseLong(tfPID.getText());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnReport;
    javax.swing.JEditorPane reportPane1;
    javax.swing.JTextField tfPID;
    // End of variables declaration//GEN-END:variables
}
